# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-ideas-home-assignment"
client_id = "eee2db089c97042222028bdfa08a3e7c"
application_url = "https://inspector-flying-how-remained.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://inspector-flying-how-remained.trycloudflare.com/auth/callback",
  "https://inspector-flying-how-remained.trycloudflare.com/auth/shopify/callback",
  "https://inspector-flying-how-remained.trycloudflare.com/api/auth/callback",
  "https://inspector-flying-how-remained.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "urielofir.myshopify.com"
